AWSTemplateFormatVersion: 2010-09-09
Description: Set up the API sync between Cloud One Conformity and the AWS Well Architected Tool
Parameters:
  ExternalId:
    Type: String
    Description: Your Conformity Organization's External Id. See https://cloudone.trendmicro.com/docs/conformity/api-reference/tag/Organisations#paths/~1organisation~1external-id/get for more details
    NoEcho: true
  Workload:
    Type: String
    Description: ARN of the Well-Architected Review to synchronize. See https://console.aws.amazon.com/wellarchitected/home for more details
    NoEcho: true
  CloudOneAccountId:
    Type: String
    Description: Cloud One Account Id of the AWS account containing the Well Architected Review to synchronize (can be obtained from Conformity Dashboard)
    NoEcho: true
  CloudOneRegion:
    Type: String
    Description: Cloud One Conformity service region, i.e same region as your Cloud One Account
    Default: trend-us-1
    AllowedValues:
      - us-1
      - trend-us-1
      - au-1
      - ie-1
      - sg-1
      - in-1
      - jp-1
      - ca-1
      - de-1
  CloudOneAPIKey:
    Type: String
    Description: Cloud One API Key with Admin Access
    NoEcho: true
  ConformityAccountId:
    Type: String
    Description: Conformity AWS Account Id (can be obtained from the Conformity Dashboard)
    NoEcho: true
  Environment:
    Type: String
    Description: Provide the environment on which the sync will happen, i.e Sandbox, Staging, Production
  Owner:
    Type: String
    Description: Provide the role owner's email address
Resources:
  WorkloadArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /TrendMicro/CloudOne/Conformity/wellarchitected-sync/WorkloadArn
      DataType: text
      Type: String
      Description: ARN of the Well-Architected Review to synchronize. See https://console.aws.amazon.com/wellarchitected/home for more details
      Value:
        Ref: Workload
  C1AccountId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /TrendMicro/CloudOne/Conformity/wellarchitected-sync/C1AccountId
      DataType: text
      Type: String
      Description: Cloud One Account Id of the AWS account containing the Well Architected Review to synchronize (can be obtained from Conformity Dashboard)
      Value:
        Ref: CloudOneAccountId
  C1CRegion:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /TrendMicro/CloudOne/Conformity/wellarchitected-sync/C1CRegion
      DataType: text
      Type: String
      Description: Cloud One Conformity service region, i.e same region as your Cloud One Account
      Value:
        Ref: CloudOneRegion
  C1APIKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: C1APIKey
      Description: Cloud One API Key with Admin Access
      SecretString:
        Ref: CloudOneAPIKey
  C1ConformitySyncPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: C1ConformitySyncPolicy
      Description: Allows updating the well-architected review
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "wellarchitected:GetAnswer"
              - "wellarchitected:UpdateAnswer"
            Resource:
              Ref: Workload
  C1ConformitySyncRole:
    Type: AWS::IAM::Role
    DependsOn:
      - C1ConformitySyncPolicy
    Properties:
      RoleName: C1ConformitySyncRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  [":", ["arn:aws:iam:", Ref: ConformityAccountId, "root"]]
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: ExternalId
      ManagedPolicyArns:
        - Ref: C1ConformitySyncPolicy
      Tags:
        - Key: "Name"
          Value: "C1ConformitySyncRole"
        - Key: "Role"
          Value: "Allows Cloud One Conformity to update a Well Architected review"
        - Key: "Environment"
          Value:
            Ref: Environment
        - Key: "Owner"
          Value:
            Ref: Owner
  C1ConformitySyncRoleArn:
    Type: AWS::SSM::Parameter
    DependsOn:
      - C1ConformitySyncRole
    Properties:
      Name: /TrendMicro/CloudOne/Conformity/wellarchitected-sync/C1ConformitySyncRoleArn
      DataType: text
      Type: String
      Description: Conformity AWS Account Id
      Value:
        Fn::GetAtt: [C1ConformitySyncRole, Arn]
  C1ConformitySyncSecretsPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn:
      - C1APIKey
    Properties:
      ManagedPolicyName: C1ConformitySyncSecretsPolicy
      Description: Allows accessing the Cloud One API Secret
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:DescribeSecret"
              - "secretsmanager:GetSecretValue"
            Resource:
              Ref: C1APIKey
  C1ConformitySyncParametersPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: C1ConformitySyncParametersPolicy
      Description: Allows accessing the wellarchitected-sync lambda parameters under /TrendMicro/CloudOne/Conformity/wellarchitected-sync
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ssm:GetParameter"
            Resource:
              Fn::Join:
                [
                  ":",
                  [
                    "arn",
                    Ref: AWS::Partition,
                    "ssm",
                    Ref: AWS::Region,
                    Ref: AWS::AccountId,
                    "parameter/TrendMicro/CloudOne/Conformity/wellarchitected-sync/*",
                  ],
                ]
  C1ConformitySyncLambdaRole:
    Type: AWS::IAM::Role
    DependsOn:
      - C1ConformitySyncRole
      - C1ConformitySyncSecretsPolicy
      - C1ConformitySyncParametersPolicy
    Properties:
      RoleName: C1ConformitySyncLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Ref: C1ConformitySyncSecretsPolicy
        - Ref: C1ConformitySyncParametersPolicy
  C1ConformitySyncUpdateReview:
    Type: AWS::Lambda::Function
    DependsOn:
      - C1ConformitySyncLambdaRole
      - C1ConformitySyncRole
    Properties:
      Description: Updates the Well-Architected Review located at WorkloadArn
      FunctionName: C1ConformitySyncUpdateReview
      Role:
        Fn::GetAtt: [C1ConformitySyncLambdaRole, Arn]
      Runtime: python3.9
      Handler: index.lambda_handler
      PackageType: Zip
      Timeout: 10
      Code:
        ZipFile: |
          import os
          import boto3
          import logging
          import json
          import urllib.request

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          secretsClient = boto3.client('secretsmanager')
          ApiKey = secretsClient.get_secret_value(SecretId=f'C1APIKey')['SecretString']

          parametersClient = boto3.client('ssm')
          WorkloadArn = parametersClient.get_parameter(Name='/TrendMicro/CloudOne/Conformity/wellarchitected-sync/WorkloadArn')['Parameter']['Value']
          AccountId = parametersClient.get_parameter(Name='/TrendMicro/CloudOne/Conformity/wellarchitected-sync/C1AccountId')['Parameter']['Value']
          RoleArn = parametersClient.get_parameter(Name='/TrendMicro/CloudOne/Conformity/wellarchitected-sync/C1ConformitySyncRoleArn')['Parameter']['Value']
          Region = parametersClient.get_parameter(Name='/TrendMicro/CloudOne/Conformity/wellarchitected-sync/C1CRegion')['Parameter']['Value']

          def lambda_handler(event, context):
            
            header = {
              "Content-Type": "application/vnd.api+json",
              "api-version": "v1",
              "Authorization": f"ApiKey {ApiKey}"
            }
            logger.info(f'Header created: {header}')

            arguments = {
              "meta": {
                "accountId": f'{AccountId}',
                "roleArn": f'{RoleArn}',
                "workloadArn": f'{WorkloadArn}'
              }
            }
            encodedBody = json.dumps(arguments).encode('utf-8')
            logger.info(f'Body created: {encodedBody}')

            apiEndpoint = f'https://conformity.{Region}.cloudone.trendmicro.com/api/well-architected-tool/sync'
            logger.info(f'Api Endpoint: {apiEndpoint}')

            request = urllib.request.Request(url=apiEndpoint, data=encodedBody, headers=header, method='POST')
            response = urllib.request.urlopen(request)

            decodedResponse = response.read().decode('utf-8')
            logger.info(f'Response was: {decodedResponse}')
      TracingConfig:
        Mode: Active
      Tags:
        - Key: "Name"
          Value: "C1ConformitySyncLambdaRole"
        - Key: "Role"
          Value: "Updates the Well-Architected Review located at WorkloadArn"
        - Key: "Environment"
          Value:
            Ref: Environment
        - Key: "Owner"
          Value:
            Ref: Owner
Outputs:
  LambdaFunctionName:
    Description: Use this name for invocation, i.e with the AWS CLI or AWS CloudShell
    Value:
      Fn::GetAtt: [C1ConformitySyncUpdateReview, Arn]
